spec:
  template:
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: /api/version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /api/version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30